// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetLogger():Promise<wails.WailsLogger>;

export function Greet(arg1:string):Promise<string>;

export function StartScan(arg1:wails.WSMessage):Promise<void>;

export function StopScan():Promise<void>;

export function WriteLog(arg1:string):Promise<void>;
