// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogger() {
  return window['go']['main']['SimpleApp']['GetLogger']();
}

export function Greet(arg1) {
  return window['go']['main']['SimpleApp']['Greet'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['SimpleApp']['StartScan'](arg1);
}

export function StopScan() {
  return window['go']['main']['SimpleApp']['StopScan']();
}

export function WriteLog(arg1) {
  return window['go']['main']['SimpleApp']['WriteLog'](arg1);
}
