// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLogger():Promise<main.WailsLogger>;

export function Greet(arg1:string):Promise<string>;

export function StartScan(arg1:main.WSMessage):Promise<void>;

export function WriteLog(arg1:string):Promise<void>;
