// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetLogger():Promise<app.WailsLogger>;

export function Greet(arg1:string):Promise<string>;

export function StartScan(arg1:app.WSMessage):Promise<void>;

export function StopScan():Promise<void>;

export function WriteLog(arg1:string):Promise<void>;
